language: node_js

node_js:
  - "9"

cache:
  apt: true
  directories:
    - node_modules

addons:
  apt:
    packages:
      - graphicsmagick

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  ssh_known_hosts: github.com

before_install:
  # Set Git config
  - git config --global user.name "牟勇"
  - git config --global user.email "my24251325@gmail.com"
  - git config --global push.default simple
  - npm rebuild node-sass;

script:
  # Clone the repository
  - git clone https://${GH_TOKEN}@github.com/mouyong/hexo-blog.git .deploy_git -v
  # Update blog.
  - git --version
  - git remote add -f blog https://${GH_TOKEN}@github.com/mouyong/hexo-md.git
  - git fetch blog
  - git subtree add --prefix=source/blog blog/master --squash
  # Install dependencies
  - npm install --global hexo
  - npm install --no-optional
  # - npm info hexo-renderer-marked

after_script:
  - hexo generate && gulp
  - cp -r public/blog/* public/articles/
  - cp -r public/* .deploy_git/
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force

branches:
  only:
    - master